import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={inter.className}>
        <Header />
        {/* <ThemeContext.Provider valcue={theme}> */}
        {children}
        {/* </ThemeContext.Provider> */}
        <Footer />
      </body>
    </html>
  );
}
